### ISSUE TITLE
New release?

### ISSUE THREAD

**Issue by astrofrog** [astropy/pytest-remotedata#19]
@drdavella - could you do a new release? The latest stable version doesn't include the fixes to the mirror infrastructure, so builds are failing on astropy master again due to this.

**Comment by drdavella** [comment]
Yes I hope to do one today. I need to get #18 into this release too.

**Comment by drdavella** [comment]
Closing this since [pytest-remotedata-0.2.0](https://pypi.python.org/pypi/pytest-remotedata/0.2.0) was released last week.
