### ISSUE TITLE
Allow `remote_data` to wrap `flaky`?

### ISSUE THREAD

**Issue by keflavich** [astropy/pytest-remotedata#25]
In astroquery, we have persistent issues where the remote services are flaky, i.e., they do not always return responses.  We're now testing over a large enough grid that it is unlikely for all services to be online simultaneously ever.

As a workaround, it would be nice to use something like [flaky](https://github.com/box/flaky) or some other retry tool to re-run tests that fail for a configurable number of tries.  It would be convenient if this were made a configurable option of `remote_data`.  Might this be possible?  I haven't wrapped my head around the pytest infrastructure enough to understand whether it is.

**Comment by drdavella** [comment]
It looks like there's already `pytest` integration for `flaky`: https://github.com/box/flaky (you might already know that, but this is completely new to me).

There may be a way to automatically integrate flaky's features with the `remotedata` plugin, but it would require a little bit of research. Is just using the `@flaky` decorator not sufficient?

**Comment by keflavich** [comment]
Well, I was hoping we could just overload the `remote_data` plugin at import time to have `max_runs=3` or something like that and apply it universally across all astroquery tests.

However, my experimentation at the moment shows that the flaky services are possibly too flaky to make this worthwhile.

**Comment by bsipocz** [comment]
I'm closing this and suggest to use `pytest-rerunfailures` for flaky tests (it also support the flaky marker to mark individual tests).
