### ISSUE TITLE
Plugin version tracking

### ISSUE THREAD

**Issue by pllim** [astropy/pytest-remotedata#29]
I just installed a dev version from #27 but installation log reported `pytest-remotedata==0.2.2.dev0`, which is inaccurate? How do I tell if I installed a dev or released version? Just curious.

**Comment by bsipocz** [comment]
I believe version numbering has been resolved since this moved to auto releases and tags, but do reopen if you think this is still an issue 

(now I have a  `pytest-remotedata-0.3.2.dev44+g782315c` version number when I install it from source)
