### ISSUE TITLE
Retire this and switch to pytest-socket?

### ISSUE THREAD

**Issue by pllim** [astropy/pytest-remotedata#36]
As brought up by @Cadair .

`pytest-socket` is at https://github.com/miketheman/pytest-socket . Although it remains to be seen how active the maintainer is.

**Comment by Cadair** [comment]
Fwiw I think that we should keep this around for interface compatibility.

**Comment by pllim** [comment]
Well, keeping it around is not the same as actively maintaining it. :wink:

**Comment by Cadair** [comment]
My suggestion is that we keep this as a wrapper to `pytest-socket` because the api of this is more aligned to what we need and many many people and tests are using that API already. We can just remove all the inner workings and keep this as a pytest shim.

**Comment by pllim** [comment]
Re: shim -- Then, the maintenance burden is still there, just a different kind, no? @drdavella , what do you think?

**Comment by pllim** [comment]
https://github.com/astropy/sphinx-automodapi/issues/160#issuecomment-1468574273

**Comment by bsipocz** [comment]
Not sure why you cross-referenced it, it seems to be less well-maintained and feature poorer. 

https://pypi.org/project/pytest-network/

Could we maybe just close this issue?

**Comment by pllim** [comment]
What about the pytest-socket in the original post? Seems to be still active and used by a bunch of other packages, it seems.

**Comment by bsipocz** [comment]
1) - what is to gain from it, is there feature parity, API compatibility, etc? It's not just about the plugin itself (it doesn't costs much to keep it around in its current state, but a lot of the ecosystem is bought into the usage, and that should be included in any cost estimations)
2) - how much effort it costs to switch, who would do that? 

IMO nothing has happened for 4 years for the switching, don't see why it's suddenly become relevant and actionable, especially if there isn't a clear answer for the two questions above. Even just considering the switch costs effort...

**Comment by pllim** [comment]
@Cadair , has your opinion changed over the years, since it was you who initially brought this up?

**Comment by pllim** [comment]
Haven't heard anything, so marking this as no-go.
