### ISSUE TITLE
Remotedata rst handler

### ISSUE THREAD

**Issue by MSeifert04** [astropy/pytest-remotedata#5]
Not sure if this would be a good fit for this package but is it possible to make a code-block-like `skip-remote` directive that would work like the decorator for the pytest functions, i.e. only runs the doctest if `--remote-data` has been specified?

**Comment by astrofrog** [comment]
I might be misunderstanding, but does this not already exist?

http://docs.astropy.org/en/stable/development/testguide.html?highlight=REMOTE_DATA#working-with-data-files

specifically:

```python
>>> datafile = get_data_filename('hash/94935')  # doctest: +REMOTE_DATA
```

this works in docstrings and in rst files.

**Comment by MSeifert04** [comment]
Ah, I haven't seen that one. I was actually thinking of something like this:
```
.. skip-no_remote::
   >>> code that does something with remote-data
   >>> more code that relies on the remote-data access earlier.
```
But `+REMOTE_DATA` would also work, it's just more verbose.

**Comment by bsipocz** [comment]
afaik we don't yet have a directive that would work for a block of doctest, either for remote-data or for float_cmp. 

Here is the related issue: https://github.com/astropy/astropy/issues/2662

**Comment by astrofrog** [comment]
Ah yes that would be cool!

**Comment by drdavella** [comment]
I think these probably actually belong in https://github.com/astropy/pytest-doctestplus, although any directive dealing with remote data will introduce a dependency on this plugin.

**Comment by bsipocz** [comment]
all of these will be part of ``pytest-astropy``, so cross dependency shouldn't be a problem I think.

**Comment by drdavella** [comment]
@bsipocz while that is true, the main motivation for breaking these into separate plugins is to make them available to packages a la carte, right? In any case it shouldn't be a big deal because it can just be an optional dependency.

My main point is that anything that defines a new doctest directive doesn't belong here: it belongs in [pytest-doctestplus](https://github.com/astropy/pytest-doctestplus).

**Comment by astrofrog** [comment]
I agree that this belongs in doctestplus, with a dependency on this package

**Comment by MSeifert04** [comment]
will you open an issue there or should I?

**Comment by drdavella** [comment]
I created two new issues there and will close this one:
https://github.com/astropy/pytest-doctestplus/issues/2
https://github.com/astropy/pytest-doctestplus/issues/3

**Comment by MSeifert04** [comment]
Thanks @drdavella
