### ISSUE TITLE
Consider releasing a new version

### ISSUE THREAD

**Issue by eerovaher** [astropy/pytest-remotedata#57]
Pull requests #48 and #53 removed the dependency on `six`, but there haven't been any releases of `pytest-remotedata` since they were merged. This means that `six` is still a dependency in practice until a new version is released.

Related to this, the change log should be updated.

**Comment by pllim** [comment]
Yeah, I think we should. Sorry this fell off the cracks.

**Comment by pllim** [comment]
TODO:

1. Add a auto release by tag workflow like pytest-doctestplus
2. Update change log
3. Hook up GitHub Release to Zenodo
4. Add a release page to Wiki
5. Tag a major release

**Comment by pllim** [comment]
v0.3.3 is released to PyPI.
