### ISSUE TITLE
BUG: cron is not running for this repo

### ISSUE THREAD

**Issue by bsipocz** [astropy/pytest-remotedata#63]
I don't see any recent runs in the logs, and CI is not picked up for new PRs

**Comment by bsipocz** [comment]
The workflow was disabled due to inactivity. I've enabled it again, but let's keep this issue open until the next cron run is picked up.

**Comment by pllim** [comment]
It ran. Thanks for fixing this!

https://github.com/astropy/pytest-remotedata/actions/runs/3167281525
